package com.mycompany.myapp;


import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import com.mycompany.gui.AccueilPage;
import com.mycompany.gui.Affichage;
import com.mycompany.gui.AjoutAvisForm;
import com.mycompany.gui.AjoutDealForm;
import com.mycompany.gui.AjoutEventForm;
import com.mycompany.gui.StarRating;
import com.mycompany.gui.allAdsCompany;
import com.mycompany.gui.pageCompany;
import com.mycompany.gui.pageUser;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
       // Affichage a = new Affichage();
      //  a.Affichage();
      AjoutAvisForm b = new AjoutAvisForm();
      b.getF().show();
    




// AjoutDealForm a = new AjoutDealForm()
       // AjoutEventForm a = new AjoutEventForm();
       // a.getF().show();
        
//        *****************************************
//pour Ads
//allAdsCompany all=new allAdsCompany();
//all.getF1().show();
//        ***************
//**********pour Company
//pageCompany u=new pageCompany();
//u.start(theme);
//*******************************
//************pour User
//pageUser Use=new pageUser();
//Use.start(theme);
//        ***********wajdi
//        AccueilPage h = new AccueilPage();
//         h.getF().show();
  
    
    
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
